spring.application.name=CycleNestOrchestrator

spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=5
# Azure Cosmos DB
spring.cloud.azure.cosmos.endpoint=https://cosmosdbitems.documents.azure.com:443/
spring.cloud.azure.cosmos.database=cwk
spring.cloud.azure.cosmos.key=${COSMOS_DB_KEY}